# -*- coding: utf-8 -*-
"""Actividad de aprendizaje Integrales por métodos numéricos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpnM5I3vUJsqK1VV8KbeZbq0NtC_cPg7
"""

import numpy as np
import matplotlib.pyplot as pl

paso = .01
p = np.arange(-1,1,paso)

ft = np.sin(np.sqrt(3)*p)*np.tan(p)

pl.plot(p, ft, 'r')
pl.fill_between(p,ft,color=(1,.616,0,.459))
pl.title("sin[3^(1/2)t]tan[t]")
pl.show()

AreaFt = np.sum(paso*ft)

print("El area bajo la curva es:", AreaFt)