# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHyqpwFSsBmjR_THn_rg1BNxNX0yf8Yc
"""

#Actividad Limites, Derivadas e Integrales

#Limites


from sympy import symbols, limit, sqrt
import math
print('Encuentra el siguiente Limite:')
x = symbols('x')
lim = limit(( (x**2) - 4)/((sqrt(x + 7) - (3 / 2)*(sqrt(x + 2)))), x, 2)
print(f'El Limite de es {lim}')

#Derivadas

from sympy import symbols, diff, exp, tan, sin, exp


x = symbols('x')
diff((tan((exp(2*sin(x)))/(4*x)))**(sqrt(x)), x)

#Integrales

from sympy import symbols, integrate, sqrt
from sympy.plotting import plot

x = symbols('x')

plot(sqrt(1 + (x**3)), (x,-5,5))

integrate(sqrt(1 + (x**3)), (x, -1,1))

import math
import numpy as np
import matplotlib.pyplot as pl
fx = []
area2 = 0
def fun1(x):
  return math.sqrt(1 + x ** 3)
paso = .01
p = np.arange(-1,1,paso)
ft = np.sqrt(1 + p ** 3)
for h in p:
    y = fun1(h)
    fx.append(y)
    area2 += paso*y

fig, ax = pl.subplots()
ax.plot(p,fx)
ax.fill_between(p,ft,color=(1, 0.984, 0, .459))

print('El area bajo la curva con ciclos es:', area2)