# -*- coding: utf-8 -*-
"""MCD de dos numers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zP3WEnGFIcz2nxRAVbqwlnuXVHZrEkhR
"""

print('Hola, vamos a calcular el Maximo Comun Divisor de dos numeros enteros, a y b.')
a = int(input('Por favor ingresa el valor de a:'))
print(f'El valor de a es: {a}')
b = int(input('Por favor ingresa el valor de b:'))
print(f'El valor de b es: {b}')

a = abs(a)
b = abs(b)

q = a//b
r = a - b*q
while r != 0 :
  a = b
  b = r
  q = a//b
  r = a - b*q
print("El máximo común divisor es: ", b)